fathom_version: latest
fathom_bin: fathom-linux-amd64
fathom_download_url: https://github.com/usefathom/fathom/releases/download/{{ fathom_version }}/{{ fathom_bin }}
fathom_bin_path: /usr/bin/fathom
