---
- block:
  - name: Create databases for sites
    mysql_db:
      name: "fathom_{{ item.key | underscore }}_{{ env }}"
      state: present
      login_host: "{{ site_env.db_host }}"
      login_user: "{{ mysql_root_user }}"
      login_password: "{{ mysql_root_password }}"
    with_dict: "{{ wordpress_sites }}"

  - name: Create/assign database user to db and grant permissions
    mysql_user:
      name: "fathom_{{ item.key | underscore }}"
      password: "{{ vault_wordpress_sites[item.key].fathom.db_password }}"
      host: "{{ site_env.db_user_host }}"
      append_privs: yes
      priv: "fathom_{{ item.key | underscore }}_{{ env }}.*:ALL"
      state: present
      login_host: "{{ site_env.db_host }}"
      login_user: "{{ mysql_root_user }}"
      login_password: "{{ mysql_root_password }}"
    with_dict: "{{ wordpress_sites }}"

  when: site_uses_local_db and item.value.fathom.enabled | default(true)
